# Generated by Django 2.1.5 on 2019-01-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='teamroles',
            field=models.ManyToManyField(null=True, related_name='team_members', to='teams.TeamRole'),
        ),
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('TeamMember', 'TeamMember'), ('AppMember', 'AppMember')],
                                   default='TeamMember', max_length=32),
        ),
    ]
