# Generated by Django 2.1.5 on 2019-01-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0002_auto_20190127_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='teamroles',
            field=models.ManyToManyField(related_name='team_members', to='teams.TeamRole'),
        ),
    ]
