# Generated by Django 2.1.5 on 2019-04-17 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0004_auto_20190201_1248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='label',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='label',
            name='org',
        ),
        migrations.RemoveField(
            model_name='label',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='visit_level',
        ),
        migrations.AddField(
            model_name='member',
            name='access_level',
            field=models.IntegerField(default=10, verbose_name='访问权限'),
        ),
        migrations.AlterField(
            model_name='member',
            name='source_type',
            field=models.CharField(choices=[('team', 'team'), ('application', 'application'), ('project', 'project')], max_length=32, verbose_name='member type ，比如team、project、app等'),
        ),
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('TeamMember', 'TeamMember'), ('AppMember', 'AppMember'), ('ProjectMember', 'ProjectMember')], max_length=32, verbose_name='成员类型'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(null=True, verbose_name='描述信息'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='TeamName'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='teamroles',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('source_id', 'source_type', 'user')},
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='TeamRole',
        ),
    ]
