# Generated by Django 2.2.10 on 2020-05-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_merge_20190508_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamNotification',
        ),
        migrations.DeleteModel(
            name='TeamSetting',
        ),
    ]
