# Generated by Django 2.1.5 on 2019-04-17 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0005_auto_20190418_0746'),
        ('orgs', '0005_auto_20190418_0728'),
        ('applications', '0005_appspec_dependency'),
        ('features', '0002_auto_20190418_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('important', models.IntegerField(verbose_name='重要性')),
                ('priority', models.IntegerField(verbose_name='优先级')),
                ('estimate_time', models.IntegerField(verbose_name='时间预估')),
                ('progress', models.IntegerField(verbose_name='进度')),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('closed_at', models.DateTimeField(null=True, verbose_name='关闭时间')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_workitems', to='applications.Application', verbose_name='关联应用')),
                ('assignee_users', models.ManyToManyField(related_name='user_workitems', to=settings.AUTH_USER_MODEL, verbose_name='开发人员')),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_workitems', to=settings.AUTH_USER_MODEL, verbose_name='关闭人')),
                ('created_by', models.ForeignKey(on_delete=models.SET(-999), to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_workitems', to='features.Feature', verbose_name='关联开发需求')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_workitems', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_workitem', to='workitems.WorkItem', verbose_name='父工作项')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_workitems', to='teams.Team', verbose_name='关联小组')),
            ],
            options={
                'verbose_name': '工作项表',
                'db_table': 'workitems',
            },
        ),
    ]
