# Generated by Django 2.1.5 on 2019-05-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workitems', '0003_auto_20190508_1217'),
        ('workitems', '0003_auto_20190507_1705'),
    ]

    operations = [
    ]
