# Generated by Django 2.1.5 on 2019-05-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workitems', '0005_auto_20190528_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='description_html',
            field=models.TextField(blank=True, null=True, verbose_name='描述HTML'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='end_date',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='结束日期YYYYMMDD'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='estimate_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='时间预估'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='进度'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='start_date',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='开始日期YYYYMMDD'),
        ),
    ]
