# Generated by Django 2.1.5 on 2019-09-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workitems', '0006_auto_20190529_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='estimate_time',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='时间预估'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='progress',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='进度'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='type',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('9', '9')], max_length=2, null=True),
        ),
    ]
