# Generated by Django 2.1.5 on 2019-05-08 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0006_auto_20190429_2326'),
        ('projects', '0003_auto_20190506_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='迭代名称')),
                ('description', models.TextField(null=True, verbose_name='迭代描述')),
                ('start_date', models.CharField(max_length=8, verbose_name='迭代开始日期YYYYMMDD')),
                ('end_date', models.CharField(max_length=8, verbose_name='迭代结束日期YYYYMMDD')),
                ('status',
                 models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], max_length=2, verbose_name='迭代状态')),
                ('created_by', models.ForeignKey(on_delete=models.SET(-999), to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='own_iterations', to=settings.AUTH_USER_MODEL,
                                            verbose_name='迭代责任人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='project_iterations', to='projects.Project',
                                              verbose_name='关联项目')),
            ],
            options={
                'db_table': 'iterations',
            },
        ),
    ]
