# Generated by Django 2.1.5 on 2019-05-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterations', '0002_auto_20190523_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='status',
            field=models.CharField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], max_length=2, null=True, verbose_name='迭代状态'),
        ),
    ]
