# Generated by Django 2.1.5 on 2019-01-26 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='orgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
