# Generated by Django 2.1.5 on 2019-04-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orgs', '0002_auto_20190126_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo', verbose_name='Logo'),
        ),
    ]
