# Generated by Django 2.1.5 on 2019-04-17 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0003_organization_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('project', 'Project'), ('wiki', 'Wiki'), ('test', 'Test')], max_length=32)),
                ('role', models.CharField(choices=[('Admin', 'Project'), ('Member', 'Member')], max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productroles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'db_table': 'ProductRoles',
            },
        ),
    ]
