# Generated by Django 2.1.5 on 2019-04-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_productrole'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productrole',
            table='productroles',
        ),
    ]
