# Generated by Django 2.1.5 on 2019-04-29 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0005_auto_20190418_0728'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productrole',
            unique_together={('user', 'product')},
        ),
    ]
