# Generated by Django 2.1.5 on 2019-05-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_auto_20190509_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
    ]
