# Generated by Django 2.1.5 on 2019-05-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_remove_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo', verbose_name='Logo'),
        ),
    ]
