# Generated by Django 2.1.5 on 2019-05-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190507_1705'),
        ('users', '0002_auto_20190508_1217'),
    ]

    operations = [
    ]
