# Generated by Django 2.1.5 on 2019-05-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190509_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name'),
        ),
    ]
