# Generated by Django 2.1.5 on 2019-01-30 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('orgs', '0002_auto_20190126_1056'),
        ('teams', '0003_auto_20190130_1456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='app_name')),
                ('description', models.TextField(verbose_name='app_desc')),
                ('type', models.CharField(choices=[('mircoservice', ''), ('web', ''), ('batch', ''), ('j2se', '')],
                                          max_length=16, verbose_name='app_type')),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=2,
                                            verbose_name='app_status')),
            ],
            options={
                'verbose_name': 'application',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSpec',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                     related_name='spec', serialize=False,
                                                     to='applications.Application')),
                ('service_id', models.CharField(max_length=128, unique=True, verbose_name='app_service_id')),
                ('description', models.TextField(verbose_name='app_spec_desc')),
                ('created_by', models.ForeignKey(on_delete=models.SET(-999), to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
            options={
                'verbose_name': 'app_spec',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                     related_name='repository', serialize=False,
                                                     to='applications.Application')),
                ('type', models.CharField(choices=[('git', 'git'), ('svn', 'svn')], max_length=8)),
                ('web_url', models.CharField(max_length=128, null=True, verbose_name='web_url')),
                ('http_url', models.CharField(max_length=128, verbose_name='web_url')),
                ('ssh_url', models.CharField(max_length=128, null=True, verbose_name='web_url')),
                ('branch', models.CharField(max_length=128, null=True)),
                ('auth_type', models.CharField(choices=[('pwd', 'pwd'), ('token', 'token')], max_length=8,
                                               verbose_name='auth_type')),
                ('auth_token', models.CharField(max_length=128)),
                ('auth_username', models.CharField(max_length=128)),
                ('auth_pwd', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(on_delete=models.SET(-999), to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
            options={
                'verbose_name': 'app_repo',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(-999), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
        ),
        migrations.AddField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_apps',
                                    to='teams.Member'),
        ),
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_applications',
                                    to='teams.Team'),
        ),
    ]
