# Generated by Django 2.1.5 on 2019-01-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='auth_pwd',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='auth_token',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='auth_username',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
