# Generated by Django 2.1.5 on 2019-01-30 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orgs', '0002_auto_20190126_1056'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_auto_20190130_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.RenameModel(
            old_name='ApplicationSpec',
            new_name='AppSpec',
        ),
    ]
