# Generated by Django 2.1.5 on 2019-04-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('applications', '0004_repository_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appspec',
            name='dependency',
            field=models.ManyToManyField(related_name='ref_apps', to='applications.Application', verbose_name='依赖的服务'),
        ),
    ]
