# Generated by Django 2.1.5 on 2019-04-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('applications', '0007_auto_20190428_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='http_url',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='ssh_url',
        ),
        migrations.AddField(
            model_name='repository',
            name='scm_url',
            field=models.CharField(max_length=128, null=True, verbose_name='SCM url'),
        ),
    ]
