# Generated by Django 2.1.5 on 2019-04-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0002_auto_20190428_1522'),
        ('applications', '0009_auto_20190428_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appspec',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appspec',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appspec',
            name='org',
        ),
        migrations.RemoveField(
            model_name='appspec',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='project_id',
        ),
        migrations.AddField(
            model_name='repository',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='project_repositorys', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='应用名称,唯一'),
        ),
    ]
