# Generated by Django 2.1.5 on 2019-05-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20190428_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='auth_pwd',
        ),
    ]
