# Generated by Django 2.1.5 on 2019-05-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_remove_repository_auth_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='auth_type',
            field=models.CharField(choices=[('pwd', 'pwd'), ('token', 'token')], max_length=8, null=True, verbose_name='auth_type'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='scm_url',
            field=models.CharField(max_length=128, null=True, verbose_name='SCM_url'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='type',
            field=models.CharField(choices=[('git', 'git'), ('svn', 'svn')], max_length=8, null=True),
        ),
    ]
