# Generated by Django 2.1.5 on 2019-05-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20190514_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='type',
            field=models.CharField(blank=True, choices=[('git', 'git'), ('svn', 'svn')], max_length=8, null=True),
        ),
    ]
