# Generated by Django 2.1.5 on 2019-05-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_auto_20190515_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='type',
            field=models.CharField(blank=True, choices=[('git', 'git'), ('svn', 'svn')], default='git', max_length=8, null=True),
        ),
    ]
