# Generated by Django 2.1.5 on 2019-05-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20190515_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='auth_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('pwd', 'pwd'), ('token', 'token')], max_length=8, null=True, verbose_name='auth_type'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='auth_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='branch',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='scm_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SCM_url'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='type',
            field=models.CharField(blank=True, choices=[('git', 'git'), ('svn', 'svn')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='web_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SCM主页'),
        ),
    ]
