# Generated by Django 2.1.5 on 2019-04-17 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0005_auto_20190418_0746'),
        ('orgs', '0005_auto_20190418_0728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='标签名称')),
                ('color', models.CharField(max_length=16, verbose_name='颜色 #****')),
                ('description', models.TextField(null=True, verbose_name='描述 预留')),
                ('type', models.CharField(choices=[('userlabel', 'userlabel'), ('applabel', 'applabel'), ('tasklabel', 'tasklabel'), ('featurelabel', 'featurelabel'), ('reqlabel', 'reqlabel')], max_length=16, null=True, verbose_name='类别 预留')),
                ('created_by', models.ForeignKey(on_delete=models.SET(-999), to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'labels',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='模块名称')),
                ('description', models.TextField(null=True)),
                ('created_by', models.ForeignKey(on_delete=models.SET(-999), to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='TeamName')),
                ('description', models.TextField()),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='项目LOGO')),
                ('visit_level', models.IntegerField(choices=[(90, '公开'), (10, '私有')], verbose_name='可见性 10 可见 90 不可见')),
                ('created_by', models.ForeignKey(on_delete=models.SET(-999), to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_projects', to='projects.Project', verbose_name='上级项目 预留')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_projects', to='teams.Team', verbose_name='归属团队')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='label',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='标签所属project'),
        ),
        migrations.AddField(
            model_name='label',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team', verbose_name='标签所属team'),
        ),
    ]
