# Generated by Django 2.1.5 on 2019-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='标签名称 唯一'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='模块名称'),
        ),
    ]
