# Generated by Django 2.1.5 on 2019-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190428_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='title',
            field=models.CharField(max_length=128, verbose_name='标签名称 唯一'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('title', 'project')},
        ),
    ]
