# Generated by Django 2.1.5 on 2019-05-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190506_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='logo',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
