# Generated by Django 2.1.5 on 2019-05-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190507_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述 预留'),
        ),
        migrations.AlterField(
            model_name='label',
            name='type',
            field=models.CharField(blank=True, choices=[('userlabel', 'userlabel'), ('applabel', 'applabel'), ('tasklabel', 'tasklabel'), ('featurelabel', 'featurelabel'), ('reqlabel', 'reqlabel')], max_length=16, null=True, verbose_name='类别 预留'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visit_level',
            field=models.IntegerField(choices=[(10, '公开'), (90, '私有')], verbose_name='可见性 10 可见 90 不可见'),
        ),
    ]
