# Generated by Django 2.1.5 on 2019-05-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190513_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='logo',
        ),
    ]
