# Generated by Django 2.1.5 on 2019-05-29 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('orgs', '0009_organization_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_remove_project_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(null=True, verbose_name='评论')),
                ('comment_html', models.TextField(blank=True, null=True, verbose_name='评论HTML')),
                ('relate_type',
                 models.CharField(choices=[('workitem', 'workitem'), ('feature', 'feature')], max_length=16,
                                  verbose_name='关联类型')),
                ('relate_id', models.IntegerField(verbose_name='关联ID')),
                ('created_by', models.ForeignKey(on_delete=models.SET(-999), to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
                ('project',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project',
                                   verbose_name='评论所属project')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'comments',
            },
        ),
    ]
