# Generated by Django 2.1.5 on 2019-08-28 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0009_organization_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('domain', models.URLField(max_length=256, verbose_name='域名')),
                ('header', models.TextField(blank=True, null=True, verbose_name='header')),
                ('cookie', models.TextField(blank=True, null=True, verbose_name='cookie')),
                ('created_by', models.ForeignKey(on_delete=models.SET(-999), to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
            options={
                'db_table': 'test_env',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='testenv',
            unique_together={('name',)},
        ),
    ]
