# Generated by Django 2.1.5 on 2019-09-29 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20190916_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testgroup',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='testgroup',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_group', to='test.TestGroup', verbose_name='父节点信息'),
        ),
    ]
