# Generated by Django 2.1.5 on 2019-10-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190606_1403'),
        ('test', '0006_auto_20191017_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_testCase', to='projects.Project', verbose_name='归属项目'),
        ),
    ]
