# Generated by Django 2.1.5 on 2019-05-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0002_operatelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatelog',
            name='resource',
        ),
        migrations.AddField(
            model_name='operatelog',
            name='resource_id',
            field=models.IntegerField(null=True, verbose_name='Resource_id'),
        ),
    ]
