# Generated by Django 2.1.5 on 2019-09-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esbinterfaces',
            name='server_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='服务方'),
        ),
        migrations.AddField(
            model_name='esbinterfaces',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
