# Generated by Django 2.1.5 on 2019-09-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_auto_20190916_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfacegroup',
            old_name='parentId',
            new_name='parent_id',
        ),
    ]
