# Generated by Django 2.1.5 on 2019-09-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_auto_20190916_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacegroup',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_group_application', to='applications.Application', verbose_name='归属应用'),
        ),
        migrations.AlterField(
            model_name='interfacetest',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_test_interface', to='designs.Interfaces'),
        ),
    ]
