# Generated by Django 2.1.5 on 2019-09-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_auto_20190916_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfacegroup',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='interfacegroup',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_group', to='designs.InterfaceGroup', verbose_name='父节点信息'),
        ),
    ]
