# Generated by Django 2.1.5 on 2019-09-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0008_interfacegroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=32, verbose_name='http方法'),
        ),
    ]
