# Generated by Django 2.1.5 on 2019-04-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('projects', '0002_auto_20190428_1522'),
        ('features', '0002_auto_20190418_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='attachment',
            field=models.ManyToManyField(null=True, related_name='feature_attchments', to='common.Attachment', verbose_name='需求附件'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_html',
            field=models.TextField(null=True, verbose_name='描述HTML'),
        ),
        migrations.AddField(
            model_name='feature',
            name='labels',
            field=models.ManyToManyField(related_name='label_features', to='projects.Label', verbose_name='需求标签'),
        ),
        migrations.AddField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_features', to='projects.Project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_features', to='applications.Application', verbose_name='关联应用'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='progress',
            field=models.IntegerField(null=True, verbose_name='进度'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=2),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='featurebranch',
            name='ref',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
