# Generated by Django 2.1.5 on 2019-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20190430_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='attachment',
            new_name='attachments',
        ),
        migrations.AlterField(
            model_name='feature',
            name='end_date',
            field=models.CharField(max_length=8, verbose_name='结束日期YYYYMMDD'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='start_date',
            field=models.CharField(max_length=8, verbose_name='开始日期YYYYMMDD'),
        ),
    ]
