# Generated by Django 2.1.5 on 2019-04-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20190430_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='labels',
            field=models.ManyToManyField(null=True, related_name='label_features', to='projects.Label', verbose_name='需求标签'),
        ),
    ]
