# Generated by Django 2.1.5 on 2019-05-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_auto_20190430_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='feature_attachments', to='common.Attachment', verbose_name='需求附件'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='label_features', to='projects.Label', verbose_name='需求标签'),
        ),
    ]
