# Generated by Django 2.1.5 on 2019-05-08 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('iterations', '__first__'),
        ('features', '0006_auto_20190430_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='iteration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='iteration_features', to='iterations.Iteration', verbose_name='归属迭代'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='feature_attachments', to='common.Attachment',
                                         verbose_name='需求附件'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='label_features', to='projects.Label',
                                         verbose_name='需求标签'),
        ),
    ]
