# Generated by Django 2.1.5 on 2019-05-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20190516_1647'),
        ('features', '0008_merge_20190508_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='application',
        ),
        migrations.AddField(
            model_name='feature',
            name='application',
            field=models.ManyToManyField(null=True, related_name='app_features', to='applications.Application', verbose_name='关联应用'),
        ),
    ]
