# Generated by Django 2.1.5 on 2019-05-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_auto_20190516_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='application',
            new_name='applications',
        ),
    ]
