# Generated by Django 2.1.5 on 2019-05-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_auto_20190516_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description_html',
            field=models.TextField(blank=True, null=True, verbose_name='描述HTML'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='estimate_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='时间预估'),
        ),
    ]
