# Generated by Django 2.1.5 on 2019-05-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_auto_20190517_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='estimate_time',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='时间预估'),
        ),
    ]
