# Generated by Django 2.1.5 on 2019-06-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0015_auto_20190530_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurebranch',
            name='branch_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='featurebranch',
            name='ref',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featurebranch',
            name='status',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
